[package]
name = "Rust_Hello_World"
version = "0.1.0"
authors = ["harold"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
